blank_issues_enabled: false

contact_links:
  - name: Contribution Guidelines
    url: https://github.com/airscripts/awesome-steam-deck/blob/main/CONTRIBUTING.md
    about: Curation criteria for list submissions.
