name: interaction

on:
  issues:
    types: [opened]

  pull_request:
    branches: [main]
    types: [opened]

jobs:
  interact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/first-interaction@main

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

          issue_message: |
            Hey there! Thank you kindly for filing an issue.
            I'll reply back to you as soon as I can.

          pr_message: |
            Hey there! Thank you kindly for your contribution!
            I'll review back as soon as I can.
