name: linter

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

        with:
          fetch-depth: 0

      - run: npx awesome-lint
